### ISSUE TITLE
Write protocol buffers messages to file

### ISSUE THREAD

**Issue by david4096** [Arc39/vcf_to_ga#2]
A function for writing the processing results to disk. If it can accept an argument for the format, we can do both JSON and .pb.

**Comment by david4096** [comment]
This should work such that there is a file for each type with the ID as the filename. You could use names or directories to store the files. So the input would be a VCF, and the output a directory that will be filled with a directory tree like:

This makes a file for each unique object and stores them in a directory hierarchy so its clear which variants belong to which variant set.

```
output/
  variant_sets/
      abcd-1234.pb
      abcd-1234/
        variants/
            abcd-1235.pb
            ...
        calls/
             abcd-1236.pb
        callsets/
             abcd-1237.pb
```

**Comment by david4096** [comment]
Try `os.mkdir`. And for writing protocol buffers messages to file use `SerializeToString()` when you're writing to the file.

**Comment by Arc39** [comment]
https://github.com/Arc39/vcf_to_ga/commit/e3279acec78d451dfb1bfe6ba531f5b2170370c3

Not going to close the issue yet, because while it works, I feel I need to definitely simplify the process.  ~~Also I just realized I put the file extensions as .proto instead of .pb.  Will change that tomorrow.~~

Nevermind, I fixed it now.
